

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    environment:
      MYSQL_ROOT_PASSWORD: RishiBhat@123
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_DATABASE: user_management
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql


  springboot:
    build: .
    container_name: docker_spring_boot
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_management
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8080"
volumes:
    mysql_data: {}






